style:
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    excludeGuardClauses: true
  WildcardImport:
    active: false
  MagicNumber:
    ignoreEnums: true
    ignoreAnnotation: true
  MaxLineLength:
    active: false