quarkus:
  datasource:
    devservices:
      init-script-path: "/dev/init.sql"
  http:
    port: 16458
    enable-compression: true

app-config:
  debug: true # 如果为 [true] 则跳过token和url认证
  login-api-path: "/auth/login"
